import './globals.css';
import type { Metadata } from 'next';
import { AuthProvider } from './provider/Providers';

import { cardo, arial, inter } from '@/fonts/font';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${cardo.variable} ${arial.variable} ${inter.variable}`}>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
