import './globals.css';
import type { Metadata } from 'next';
import { getServerSession } from 'next-auth';
import SessionProvider from '@/components/providers/SessionProvider';
import Provider from '@/components/providers/Provider';
import { cardo } from '@/fonts/font';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const authSession = await getServerSession();

  return (
    <html lang="en">
      <body className={cardo.className}>
        <SessionProvider session={authSession}>
          <Provider>{children}</Provider>
        </SessionProvider>
      </body>
    </html>
  );
}
